### ISSUE TITLE
No schematic

### ISSUE THREAD

**Issue by thiseldo** [arananet/TzxDuino-Reloaded#2]
There is no schematic or KiCAD/Eagle files.

**Comment by corbym** [comment]
I agree, we need a kicad or eagle file to diagnose issues. I myself am having issues with the SD card slot and without a diagram it's hard to know what's going on.

Please re-open the issue.

**Comment by kalinkaata** [comment]
Agreed. Please reopen the issue. I'm trying to build my own version with some tweaks, and the schematic would be welcome. Especially if we want to remain compatible with the firmware - so to retain the same pin configuration as much as possible.

**Comment by nogarth** [comment]
> I agree, we need a kicad or eagle file to diagnose issues. I myself am having issues with the SD card slot and without a diagram it's hard to know what's going on.
> 
> Please re-open the issue.

ive built 3 all diffrent nanos all other parts what was suggested 5 diffrent sd cards and all  come back **no sd card** wasted money onm this project and cant even diagnose without schematic
